### PR TITLE
Star Pattern challenges using loops!

### PR DESCRIPTION
**Pull request by Rehan-Khan-Engineer**
This contains a total of 5 star pattern challenges that were given to me by my mentors while learning Loops! 
Live Link : https://rehan-khan-engineer.github.io/Star-Pattern-Challenges/

### CODE REVIEW

**Review by ManSOorcode — APPROVED** [review]

**Review by mujeeb100 — APPROVED** [review]
Nice!

**Review by OSAMA478 — APPROVED** [review]
Good...

**Comment by murtazshaikh** [comment]
Awesome @Rehan-Khan-Engineer

**Review by murtazshaikh — APPROVED** [review]
Nicely Covered

**Review by syedabdullahali — APPROVED** [review]

**Pull request merged**
